### ISSUE TITLE
Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by msfragala** [mskelton/wait-for-vercel-action#1]
Just tried adding this to a workflow, and consistently hits errors saying `Cannot read property 'id' of undefined`. Here's my config for reference:

```yml
name: Lighthouse CI
on: pull_request
jobs:
  run-lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        run: yarn install

      - name: Wait for Vercel deployment
        uses: mskelton/wait-for-vercel-action@v1
        id: vercel
        with:
          prod-url: ${{ secrets.PROD_URL }}
          token: ${{ secrets.VERCEL_TOKEN }}

      - name: Audit URLs with Lighthouse
        uses: treosh/lighthouse-ci-action@v3
        with:
          configPath: .lighthouserc.js

```

**Comment by mskelton** [comment]
Looks like `pull_request` has a different webhook payload than the `push` event.  When creating this, I was using the `push` event.

Would switching to the push event work for your use case?  If not, we would need to detect the sha in a better way.  Looks like `GITHUB_SHA` might work.

**Comment by mskelton** [comment]
For reference, this is the line of code that is failing

https://github.com/mskelton/wait-for-vercel-action/blob/master/index.js#L42

**Comment by mskelton** [comment]
Closing due to lack of response

**Comment by gtsop** [comment]
Hi @mskelton  I have the same issue. I technicaly can have the push event work for me, and that's what I do as of now, but it triggers more actions than what I would like. Is there a plan to fix this? 

My use case is I'm using this action to run automated End-2-End tests on deployed version on Pull Requests. Using the push event will trigger the same action on pushes to the master branch, which I don't really want/care about.

**Comment by mskelton** [comment]
So, the first thing you could do is use the push event and exclude the master branch.  Something like this:

```yaml
on:
  push:
    branches:    
    - '!master'
```

The other thing would be to investigate if we can get the commit sha from the pull_request event. 
 Then we would update this line in the action to be a ternary based on the event type. https://github.com/mskelton/wait-for-vercel-action/blob/master/index.js#L55
