### ISSUE TITLE
Working with multiple deployments

### ISSUE THREAD

**Issue by gtsop** [mskelton/wait-for-vercel-action#6]
I have 2 vercel deployments on the same repository. The one is for the actual react application and the other is deploying a react storybook. I want to grab the application url instead of the storybook one, but unfortunatelly this actions picks up the storybook by default. Is there a way to work around this or would it require modifications in this action?

**Comment by mskelton** [comment]
Are the URLs different?  Also, could you share your Action configuration?

**Comment by gtsop** [comment]
Here is the github action:
```
name: pr-tests
on: [push]
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install modules
        run: npm i
      - name: Run tests
        run: npm test
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Vercel deployment
        uses: mskelton/wait-for-vercel-action@v1
        id: wait-for-vercel
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          team-id: study-hub
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Cypress
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_BASE_URL: ${{ steps.wait-for-vercel.outputs.url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Yes the urls are different, i have two different vercel projects linking to the same repository.

**Comment by mskelton** [comment]
So sorry about not getting back to you on this.  Looks like projectId is an option for a query string param based on their docs https://vercel.com/docs/api#endpoints/deployments/list-deployments/request-query-parameters

Would that solve your use case if we added that as an input to the action?  Then it could look like this (with whatever your project id is):

```yml
- name: Wait for Vercel deployment
        uses: mskelton/wait-for-vercel-action@v1
        id: wait-for-vercel
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          team-id: study-hub
          project-id: study-hub-project
```
